class Voyage():

    def __init__(self, airplane, destination, employees, time, flight_numbers, booking_reference):
        self.airplane = airplane
        self.destination = destination
        self.employees = employees # skoða hvernig það á að útfæra þetta því það eru nokkrir stm í hverju flugi
        self.time = time
        self.flight_numbers = flight_numbers 
        self.booking_reference = booking_reference #random number generated by our program cannot be used twice


    def __str__(self):
        return "{},{},{},{},{},{},".format(self.airplane, self.destination, self.employees, self.time, self.flight_numbers, self.booking_reference)


    def get_airplane(self):
        return self.airplane

    def get_destination(self):
        return self.destination

    def get_employees(self):
        return self.employees
    
    def get_time(self):
        return self.time

    def get_flight_numbers(self):
        return self.flight_numbers

    def get_booking_reference(self):
        return self.booking_reference
        