from Services.Airplane_services import AirplaneLL
from Services.Destination_services import DestinationLL
from Services.Employees_services import EmployeeLL
from Services.Voyage_services import VoyageLL