class Voyage():

    def __init__(self, airplane, destination, employees, time, flight_numbers, booking_reference):
        self.__airplane = airplane
        self.__destination = destination
        self.__employees = employees # skoða hvernig það á að útfæra þetta því það eru nokkrir stm í hverju flugi
        self.__time = time
        self.__flight_numbers = flight_numbers 
        self.__booking_reference = booking_reference #random number generated by our program cannot be used twice


    def __str__(self):
        return "{},{},{},{},{},{},".format(self.__airplane, self.__destination, self.__employees, self.__time, self.__flight_numbers, self.__booking_reference)


    def get_airplane(self):
        return self.__airplane

    def get_destination(self):
        return self.__destination

    def get_employees(self):
        return self.__employees
    
    def get_time(self):
        return self.__time

    def get_flight_numbers(self):
        return self.__flight_numbers

    def get_booking_reference(self):
        return self.__booking_reference
        